### PR TITLE
Create Bioplanet Pathway Gene smartapi yaml

### PR DESCRIPTION
**Pull request by rjawesome**
I tested with a pathway to gene and gene to pathway query w/ BTE.
<details>
  <summary>Example Query</summary>
  
  ```json
  {
      "message": {
          "query_graph": {
              "nodes": {
                  "n0": {
                      "ids": ["BIOPLANET:bioplanet_906"],
                      "categories":["biolink:Pathway"]
                  },
                  "n1": {
                      "ids":["NCBIGene:10053"],
                      "categories":["biolink:Gene"]
                 }
              },
              "edges": {
                  "e01": {
                      "subject": "n1",
                      "object": "n0"
                  }
              }
          }
      }
  }
  ```

</details>
<details>

  <summary>Example Response</summary>

  ```json
  {
      "workflow": [
          {
              "id": "lookup"
          }
      ],
      "message": {
          "query_graph": {
              "nodes": {
                  "n0": {
                      "ids": [
                          "BIOPLANET:bioplanet_906"
                      ],
                      "categories": [
                          "biolink:Pathway"
                      ]
                  },
                  "n1": {
                      "ids": [
                          "NCBIGene:10053"
                      ],
                      "categories": [
                          "biolink:Gene"
                      ]
                  }
              },
              "edges": {
                  "e01": {
                      "subject": "n1",
                      "object": "n0"
                  }
              }
          },
          "knowledge_graph": {
              "nodes": {
                  "BIOPLANET:bioplanet_906": {
                      "categories": [
                          "biolink:Pathway"
                      ],
                      "name": "BIOPLANET:bioplanet_906",
                      "attributes": [
                          {
                              "attribute_type_id": "biolink:xref",
                              "value": [
                                  "BIOPLANET:bioplanet_906"
                              ]
                          },
                          {
                              "attribute_type_id": "biolink:synonym",
                              "value": [
                                  "BIOPLANET:bioplanet_906"
                              ]
                          }
                      ]
                  },
                  "NCBIGene:10053": {
                      "categories": [
                          "biolink:Gene"
                      ],
                      "name": "AP1M2",
                      "attributes": [
                          {
                              "attribute_type_id": "biolink:xref",
                              "value": [
                                  "NCBIGene:10053",
                                  "ENSEMBL:ENSG00000129354",
                                  "HGNC:558",
                                  "OMIM:607309",
                                  "UMLS:C1412438",
                                  "UniProtKB:Q53GI5",
                                  "UniProtKB:Q9Y6Q5",
                                  "PR:Q9Y6Q5"
                              ]
                          },
                          {
                              "attribute_type_id": "biolink:synonym",
                              "value": [
                                  "AP1M2",
                                  "AP1M2 gene",
                                  "Q53GI5_HUMAN Adaptor-related protein complex 1, mu 2 subunit variant (Fragment) (trembl)",
                                  "AP1M2_HUMAN AP-1 complex subunit mu-2 (sprot)",
                                  "AP-1 complex subunit mu-2 (human)"
                              ]
                          }
                      ]
                  }
              },
              "edges": {
                  "59ef9087151e26ac4201763e5e4bec89": {
                      "predicate": "biolink:actively_involved_in",
                      "subject": "NCBIGene:10053",
                      "object": "BIOPLANET:bioplanet_906",
                      "attributes": [
                          {
                              "attribute_type_id": "biolink:aggregator_knowledge_source",
                              "value": [
                                  "infores:biothings-explorer"
                              ],
                              "value_type_id": "biolink:InformationResource"
                          },
                          {
                              "attribute_type_id": "biolink:primary_knowledge_source",
                              "value": [
                                  "infores:bioplanet"
                              ],
                              "value_type_id": "biolink:InformationResource"
                          },
                          {
                              "attribute_type_id": "biolink:aggregator_knowledge_source",
                              "value": [
                                  "infores:biothings-bioplanet-pathway-gene"
                              ],
                              "value_type_id": "biolink:InformationResource"
                          },
                          {
                              "attribute_type_id": "pathway_name",
                              "value": [
                                  "Disease"
                              ]
                          },
                          {
                              "attribute_type_id": "pathway_categories",
                              "value": [
                                  "Cancer",
                                  "Cell death",
                                  "Cell division",
                                  "Human Diseases",
                                  "Immune system",
                                  "Infectious disease",
                                  "Transcription",
                                  "Translation",
                                  "Transport"
                              ]
                          },
                          {
                              "attribute_type_id": "gene_symbol",
                              "value": [
                                  "AP1M2"
                              ]
                          }
                      ]
                  }
              }
          },
          "results": [
              {
                  "node_bindings": {
                      "n1": [
                          {
                              "id": "NCBIGene:10053"
                          }
                      ],
                      "n0": [
                          {
                              "id": "BIOPLANET:bioplanet_906"
                          }
                      ]
                  },
                  "edge_bindings": {
                      "e01": [
                          {
                              "id": "59ef9087151e26ac4201763e5e4bec89"
                          }
                      ]
                  },
                  "score": 0
              }
          ]
      }
  }
  ```

</details>

### CODE REVIEW

**Comment by colleenXu** [comment]
@rjawesome The title of the API needs to be changed (it's still Pathway-Disease here)

**Comment by rjawesome** [comment]
Oops should be fixed

**Comment by colleenXu** [comment]
Other issues:
* Remove subject.GENE_SYMBOL lines in operations (parameter fields) and response-mapping. (Also remember to remove the last comma in the `object.PATHWAY_NAME,object.PATHWAY_CATEGORIES,` string above that line.) BTE will retrieve gene symbols during the ID resolution steps, so it's not needed as an edge-attribute
* Predicate:
    * For pathway-gene, use "has_participant" (same as what MyGene uses for pathway-gene operations)
    * For gene-pathway, use "participates_in" 
* Modify the testExample sections:
    * For pathway-gene: 
```
        # testExamples:
        #   - qInput: "BIOPLANET:bioplanet_869"     ## Chondroitin sulfate/dermatan sulfate metabolism
        #     oneOutput: "NCBIGene:9672"                ## SDC3
```
    * For gene-pathway: 
```
        # testExamples:
        #   - qInput: "NCBIGene:1463"                                 ## NCAN
        #     oneOutput: "BIOPLANET:bioplanet_789"         ## Dermatan sulfate biosynthesis
```

**Comment by colleenXu** [comment]
@rjawesome 

Other issues:
* Remove subject.GENE_SYMBOL lines in operations (parameter fields) and response-mapping. (Also remember to remove the last comma in the `object.PATHWAY_NAME,object.PATHWAY_CATEGORIES,` string above that line.) 
    * BTE will retrieve gene symbols during the ID resolution steps, so it's not needed as an edge-attribute
    * the pathway-disease API included gene stuff because it was info explaining the relationship. For pathway-gene, gene info isn't explaining the relationship further, so it's not needed. 
* Predicate:
    * For pathway-gene, use `has_participant` (same as what MyGene uses for pathway-gene operations)
    * For gene-pathway, use `participates_in`
* Modify the testExample sections:
    * For pathway-gene: 
```
        # testExamples:
        #   - qInput: "BIOPLANET:bioplanet_869"     ## Chondroitin sulfate/dermatan sulfate metabolism
        #     oneOutput: "NCBIGene:9672"            ## SDC3
```
    * For gene-pathway: 
```
        # testExamples:
        #   - qInput: "NCBIGene:1463"                      ## NCAN
        #     oneOutput: "BIOPLANET:bioplanet_789"         ## Dermatan sulfate biosynthesis
```
* In the response-mapping, only the output and the pathway info is needed (since we're removing extra gene info)
```
  x-bte-response-mapping:
    gene:
      NCBIGene: subject.GENE_ID   ## no prefix
      pathway_name: object.PATHWAY_NAME
      pathway_categories: object.PATHWAY_CATEGORIES
    pathway:
      BIOPLANET: object.PATHWAY_ID
      pathway_name: object.PATHWAY_NAME
      pathway_categories: object.PATHWAY_CATEGORIES
```

**Comment by rjawesome** [comment]
Should be fixed!

**Comment by colleenXu** [comment]
I'm going to merge it, and then make a commit that affects this file (I looked at biolink-model and realized that they added a bioplanet ID prefix "ncats.bioplanet".....which is not the spelling I expected...).

**Comment by colleenXu** [comment]
This is what I did next (as FYI):
* made a commit to both bioplanet apis to fix the prefix for bioplanet pathway IDs https://github.com/NCATS-Tangerine/translator-api-registry/commit/0395669dfee9685031f6f5fdbe5d3ac383959bed
* went to https://smart-api.info/add-api (I already have an account with smartapi registry, I think it's my github account), and pasted the raw link for an api and pressed submit to make new apis
* went to my dashboard and pressed the "check status" buttons in the rows for both new apis to check their uptime status (all good: so the examples under the endpoints are good and returned responses!)
* used the SmartAPI registration IDs to add the apis to BTE https://github.com/biothings/BioThings_Explorer_TRAPI/commit/4c1e4fad357e0bf834a9bf8e0a72138fae26220a

The next step is for Jackson to deploy BTE changes to ITRB instances of the tools (test/testing, prod/production), I think.

**Comment by colleenXu** [comment]
And another step I just did: update the infores catalog in Translator for the new infores terms used in these two apis...

**Pull request merged**
