### PR TITLE
Added triples for Multiomics Wellness KP

### PR DESCRIPTION
**Pull request by gglusman**

### CODE REVIEW

**Comment by andrewsu** [comment]
The content of the new records looks good to me -- can you adjust the spacing to keep the style uniform?

**Comment by gglusman** [comment]
The old tabs-vs-spaces issue. Fixed, I think.

**Comment by colleenXu** [comment]
I notice something odd about this triple:
>         {
>             "underlying_api_infores": "biothings-multiomics-wellness",
>             "subject_category": "biolink:SmallMolecule",
>             "subject": "KEGG.COMPOUND:C05328",
>             "subject_name": "(S)-a-amino-omega-caprolactam",
>             "predicate": "biolink:correlated_with",
>             "object_category": "biolink:Protein",
>             "object": "UniProtKB:P35318",
>             "object_name": "CVD2_P35318"
>         },

First, BTE uses Gene here rather than Protein (the conflation of Protein -> Gene conflation decision was made by Architecture committee I think). It's in the x-bte annotation for the [operation](https://github.com/Hadlock-Lab/multiomics_wellness_kp/blob/main/multiomics_wellness.yaml#L3768) that would be used to retrieve this record. 

Second, I looked up the [UniProt ID](https://www.uniprot.org/uniprotkb/P35318/entry), and it seems to be for ADM / Pro-adrenomedullin? I don't recognize the name CVD2...This might be a minor thing...

**Comment by gglusman** [comment]
Currently our KP uses Protein, so the test triple has to reflect that. We can discuss changing the KP...
The CVD2 part in the object name refers to a panel. I agree that it would be more informative to use the actual protein name instead. Again this is how the KP is structured at the moment, and we can discuss modifying it. Meanwhile the test cases should reflect what's there, I think.

**Comment by colleenXu** [comment]
And the third triple (pasted below) doesn't have a matching operation in the x-bte annotation. And I'm not sure what these KEGG.ORTHOLOGY entities are...

>         {
>             "underlying_api_infores": "biothings-multiomics-wellness",
>             "subject_category": "biolink:MolecularActivity",
>             "subject": "KEGG.ORTHOLOGY:K00003_musicc",
>             "subject_name": "homoserine dehydrogenase [EC:1.1.1.3]",
>             "predicate": "biolink:correlated_with",
>             "object_category": "biolink:MolecularActivity",
>             "object": "KEGG.ORTHOLOGY:K11907_musicc",
>             "object_name": "type VI secretion system protein VasG"
>         }

**Comment by gglusman** [comment]
These are microbiome activities. See for example https://www.genome.jp/entry/K00003

**Comment by colleenXu** [comment]
> Currently our KP uses Protein, so the test triple has to reflect that. We can discuss changing the KP... The CVD2 part in the object name refers to a panel. I agree that it would be more informative to use the actual protein name instead. Again this is how the KP is structured at the moment, and we can discuss modifying it. Meanwhile the test cases should reflect what's there, I think.

But...the x-bte annotation controls how the KP data is processed, so Service Provider (BTE as a KP) will show this as a Gene in its response. It doesn't show this as a Protein.

**Comment by gglusman** [comment]
Will the test fail because of that?

**Comment by colleenXu** [comment]
> These are microbiome enzymatic activities. See for example https://www.genome.jp/entry/K00003

* I'm still unclear on what the "_musicc" part of the ID is.
* Looking at that entry, it doesn't seem to be specific to the microbiome. Which makes me wonder if another ID-namespace would work? (maybe that's what the _musicc is meant to be, but I can't find what K00003_musicc is...)
* Looking at that entry, it looks like there's a mapping to a GO ID. Perhaps that could be used instead (although it's also not microbiome-specific)?

<br>

Also, a validation warning will happen on the SRI tests for ID-namespaces that aren't in the biolink-model for that category (from https://github.com/TranslatorSRI/SRI_testing/blob/main/tests/onehop/README.md#general-recommendations-for-edge-test-data):

> Note that the second example above also illustrates another issue: that subject and object identifiers need to have CURIE prefix (xmlns) namespaces that map onto the corresponding category classes (i.e. are specified in the Biolink Model id_prefixes for the given category). This will be highlighted as a validation warning by the SRI Testing, but simply follows from the observation (above) the UniProtKB doesn't specifically map to biolink:NamedThing and MESH doesn't specifically map to a mixin (let alone biolink:PathologicalEntityMixin).

**Comment by colleenXu** [comment]
> Will the test fail because of that?

I don't know. 

I find it easier to have the test-triples match the categories assigned in the corresponding x-bte operations. As the main curator of x-bte annotations, I changed all of the "Protein" operations to "Gene" last year after the Gene/Protein conflation discussion in Architecture. This made things easier (don't have to keep track of both) and the operations would be used in more queries (since developers seem to be using queries with Gene more often than with Protein).

**Comment by colleenXu** [comment]
And to clarify, the main problem with the third triple isn't the ID-namespace....it's that it's not available to BTE/Service Provider since there isn't x-bte annotation for it. 

https://github.com/NCATS-Tangerine/translator-api-registry/pull/102#issuecomment-1292594069

**Comment by gglusman** [comment]
Ok, I dropped that triple for now. What else needs to be modified?

**Comment by colleenXu** [comment]
After [discussions](https://ncatstranslator.slack.com/archives/C0125JTMDHA/p1667867310273069) with Chunlei, I [adjusted](https://github.com/NCATS-Tangerine/translator-api-registry/commit/c0496629510d8ebe4f607b380cfd2ff12c90b338) Service Provider's registration so it allows multiple files for SRI testing data. 

In this PR, can you make a new json file named "sri-test-multiomics.json" in the biothings_explorer directory? And move your test-triples there?

**Comment by gglusman** [comment]
Will do.

**Comment by colleenXu** [comment]
Discussed within the Service Provider/BTE team and we decided to move forward with the "multiple files" plan. Merging this PR.

**Pull request merged**
