### PR TITLE
GTRx API YAML

### PR DESCRIPTION
**Pull request by mnarayan1**
YAML for [GTRx API](https://github.com/biothings/pending.api/issues/62). The API is located [here](https://biothings.ncats.io/gtrx).

Issues
- I couldn't find an [infores ](https://docs.google.com/spreadsheets/d/1Ak1hRqlTLr1qa-7O0s5bqeTHukj9gSLQML1-lg6xIHM/edit#gid=293462374) for GTRx, so that field is blank for now
- I couldn't find the Inxight id type in the [biolink-model](https://github.com/biolink/biolink-model/blob/master/context.jsonld) semantic types or the [ID-prefix spellings](https://github.com/biolink/biolink-model/blob/master/context.jsonld), so I'm not sure if I got the x-bte annotations right. I could use some help with that and testing if the API is working

### CODE REVIEW

**Comment by andrewsu** [comment]
* I created a new entry in the spreadsheet, so you can go ahead and use `infores:gtrx`
* regarding testing, there may be issues if the prefix isn't in the biolink-model, but have you reviewed the testing protocol at https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/README-writing-x-bte.md#testing-after-its-written ?

**Comment by mnarayan1** [comment]
I updated the yaml file with infores information.

For testing, I followed the instructions and I'm getting this error when I run a query: `Specified SmartAPI ID (123412341234) is either invalid or missing.`

Here's what my `smartapi_overrides.json` file looks like:
```
{
  "conf": {
    "only_overrides": true
  },
  "apis": {
    "123412341234": "https://raw.githubusercontent.com/mnarayan1/translator-api-registry/gtrx-yaml/gtrx/gtrx.yaml"  
  }
}
```

Here's the query I tested: 
```
curl --request POST \
  --url http://localhost:3000/v1/smartapi/123412341234/query \
  --header 'Content-Type: application/json' \
  --data '{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["257220"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}'
```

**Comment by colleenXu** [comment]
I'm reviewing this now, so I'll request some edits soon. 

I think one reason @mnarayan1 is encountering issues is because the names of the operations (`disease-drug` and `drug-disease`) don't match the names of the operations in the `$ref` under` /query.post`

```
      x-bte-kgs-operations:
      - $ref: '#/components/x-bte-kgs-operations/chemical-disease'
      - $ref: '#/components/x-bte-kgs-operations/disease-chemical'
```

because the yaml parser encounters this error, it probably isn't loading the yaml.

**Comment by colleenXu** [comment]
@mnarayan1 @andrewsu On the "INXIGHT" IDs, some questions:

1. Are these UNII IDs? When I put various IDs into the top search bar of https://drugs.ncats.io/, I see an icon indicating that these are UNII IDs. And for most of these, SRI Node Normalizer can retrieve the correct entity when given this ID with the UNII prefix. 
    * 8558G7RUTR [pyruvic acid](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UNII%3A8558G7RUTR&conflate=true)
    * 4975G9NM6T [Entacapone](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UNII%3A4975G9NM6T&conflate=true)
    * KV2JZ1BI6Z [Pyridoxine](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UNII%3AKV2JZ1BI6Z&conflate=true)
    * A3ULP0F556 [Eculizumab](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UNII%3AA3ULP0F556&conflate=true)
    * [MZ1IW7Q79D](https://drugs.ncats.io/drug/MZ1IW7Q79D#identifiers) [Valaciclovir](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UNII%3AMZ1IW7Q79D&conflate=true)
    * 66Y330CJHS Human immunoglobulin G: SRI Node Norm doesn't seem to recognize this ID but it seems to be a valid UNII. SRI Node Norm also doesn't recognize [the equivalent DrugBank / NCIT / CAS / RXCUI IDs](https://drugs.ncats.io/drug/66Y330CJHS#identifiers)
2. It looks like Inxight IDs were added as the ID namespace `ncats.drug`, since Andrew's [issue](https://github.com/biolink/biolink-model/issues/1046) on this was closed with this [commit](https://github.com/biolink/biolink-model/commit/4156768ded5f05f2180ddc5572ea032a18f4a3d8)
3. I tried using Inxight/INXIGHT/inxight and `ncats.drug` as prefixes for the IDs in SRI Node Normalizer. None of those prefixes worked. Noting this issue https://github.com/TranslatorSRI/NodeNormalization/issues/135

**Comment by colleenXu** [comment]
@mnarayan1

I've attached the edited yaml with the following changes: 
[gtrx.txt](https://github.com/NCATS-Tangerine/translator-api-registry/files/10322506/gtrx.txt)
* updated SmartAPI annotation (this is documentation I did for all the BioThings APIs recently ([example](https://github.com/NCATS-Tangerine/translator-api-registry/commit/08ad7cc361449e14cd5af70b4c861452947336fb)). Don't worry about it) 
* x-bte annotation:
    * need a different infores for the api (info.x-translator.infores) compared to the underlying resource (inside each operation). I adjusted the infores for the api and will make the edit to the infores catalog google sheet
    * all the operations here need `supportBatch: true`. In general, queries that use the /query.post endpoint can handle batch-queries (> 1 ID at a time). 
    * predicates need swapping (disease treated_by drug, drug treats disease)
    * parameter fields: the output ID field is special but right now all other fields listed will be put into the "edge" info (attributes)
        * MUST use commas between diff fields in parameters
        * MUST add all fields that will be referenced in the response-mapping section
        * can add fields that exist in only some records / seem useful to users. For an association-based record structure like this, we can add fields from any part of the record to the parameter-fields/response-mapping
* examples for testing

---

notes on testing:

* contents of my bte-trapi smartapi_overrides.json (I'm using a local copy of the Smartapi yaml)
```
{
  "conf": {
    "only_overrides": true
  },
  "apis": {
    "gtrx": "file:///Users/colleenxu/Desktop/translator-api-registry/gtrx/gtrx.yaml"
    }
}
```
* I saved my local copy of the yaml. Then I run `npm run compile` and `API_OVERRIDE=true INSTANCE_ENV=dev npm run smartapi_sync --workspace='@biothings-explorer/bte-trapi'` to set up using this local copy of the yaml. Then I run `npm start` to start up BTE.
* Then I post a query to `http://localhost:3000/v1/smartapi/gtrx/query`. Inside the request body (TRAPI query), we must use prefixed-IDs (aka curies)...

<details>
<summary>example queries</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["OMIM:250250"],
                    "categories": ["biolink:Disease"],
                    "name": "CARTILAGE-HAIR HYPOPLASIA"
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            }
        }
    }
}
```

and

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["UNII:F64QU97QCR"],
                    "categories": ["biolink:SmallMolecule"],
                    "name": "Dantrolene"
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}
```

</details>

**Comment by mnarayan1** [comment]
@colleenXu Thanks for your help! I updated my branch with your changes. 

I tried testing with the updated yaml and queries, and I'm getting this error: 

```
{
    "error": "Your input query graph is invalid",
    "more_info": "Your Input Query Graph is invalid."
}
```

I'm guessing the yaml file loaded correctly this time, but there are some issues with how I'm testing the queries themselves? This is the query I ran this time:

```
curl --request POST \
  --url http://localhost:3000/v1/smartapi/gtrx/query \
  --header 'Content-Type: application/json' \
  --data '{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["UNII:F64QU97QCR"],
                    "categories": ["biolink:SmallMolecule"],
                    "name": "Dantrolene"
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}'
```

**Comment by colleenXu** [comment]
@mnarayan1 Thanks for making these changes! I'm going to move forward and merge this PR, then [do the next steps of incorporating it into BTE](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/README-writing-x-bte.md#deploying-checking-registering-and-refreshing-registration-connecting-to-bte). 

I'm not sure why you're getting this vague error. Perhaps we could do a quick zoom meeting with screen-share to figure this out?

**Pull request merged**
