### PR TITLE
Update smartapi.yaml

### PR DESCRIPTION
**Pull request by GitHubbit**
Updates to smartapi.yaml for Multiomics Clinical Trials KP for compatibility with TRAPI 1.4 edge sources specification
@colleenXu

### CODE REVIEW

**Comment by colleenXu** [comment]
@GitHubbit I did a quick test and it seemed to work properly with BTE, which is great. Please leave it in this fork for now (we'll only merge this PR when we move all instances to TRAPI 1.4). 

We'll hopefully deploy a SmartAPI override file soon https://github.com/biothings/biothings_explorer/blob/trapi1-4-overrides/src/config/smartapi_overrides.json, which will allow the dev instance of BTE to use your fork's file and do TRAPI 1.4 source formatting properly for your KP. 

One note:
* I notice no use of "upstream_resource_ids" in your source objects. That may be fine, but you could check with data modeling / EPC to see if they want that info...

**Comment by colleenXu** [comment]
SmartAPI override file has been deployed. So BTE's dev instance should be showing the TRAPI 1.4 sources data correctly using the data in the BioThings API.

Another note:
* I think one of the edge-attributes has an `attribute_type_id` that isn't a curie: `clinicaltrials_id`. This will probably cause an error/warning in the TRAPI validator, but...well, Service Provider has a LOT of stuff that does that :P. I suggest asking data-modeling / epc group how to format the clinical trials ID properly.

**Comment by GitHubbit** [comment]
Believe this is addressed now: [https://github.com/biothings/biothings_explorer/issues/617#issuecomment-1562026459](Multiomics ClinicalTrials KP: NEEDED SmartAPI yaml edits) TRAPI 1.3 only

**Comment by colleenXu** [comment]
@GitHubbit 

I've looked at these edits, but I haven't tested them myself. I agree that they should fix the x-bte annotation issues for the registered yaml, which BTE's prod instance uses and is for TRAPI 1.3 support.

The next steps are:
* merge this PR. You should now have write permissions for this repo
* refresh the SmartAPI registration for the BioThings API. You'll need the ownership of this BioThings API's SmartAPI registration transferred to you. Chunlei posted about this [here (Translator Slack link)](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1687327054759529?thread_ts=1686941206.765469&cid=C022EL8D3AB). Then you'd refresh the registration through the dashboard (we'll help if you encounter any issues and post in #bte Translator Slack). 

And after that is testing!
* Test your KP through BTE-prod with TRAPI queries (previous posts on how in Translator Slack [here](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1685657103703609?thread_ts=1685513467.995279&cid=C022EL8D3AB) and [here](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1680247129971939?thread_ts=1680247075.792959&cid=C022EL8D3AB)). Every 10 min, BTE instances get the latest SmartAPI registry info and incorporate changes, so you may need to wait <=10 min after refreshing for your changes to be live.
* Also test your KP through the CI instance of BTE! Non-prod instances are TRAPI 1.4 and are currently linked to your fork, not the registered yaml (see [here](https://github.com/biothings/biothings_explorer/blob/9abfba188b34277cff1638ab76bad91f493703bf/src/config/smartapi_overrides.json#L7)). 
    * I suspect that the TRAPI 1.4 sources info will be wonky because the [`source.edge_sources` info is missing](https://github.com/NCATS-Tangerine/translator-api-registry/pull/116/commits/085ed25bcd0e7441404c30cb96ac67f1b6bd890c)...
    * if you change the fork's file, you don't need to refresh the registration (because your fork isn't the registered yaml). During the "every-10-min" refresh of their registry data, the non-prod instances will use the links in the overrides file to retrieve the latest versions of those yamls. So you'll just wait <=10 min and then your changes should be live for re-testing.

**Comment by colleenXu** [comment]
The registered yaml should now be working and "TRAPI 1.4", after this PR merge and https://github.com/NCATS-Tangerine/translator-api-registry/commit/59c6a562b6f8f39105819f5c6424b9b6c8a317c9. 

The override yaml in the fork is working but probably isn't "TRAPI 1.4" because the source.edge_sources info is missing.

**Pull request merged**
