### PR TITLE
Updating the representation of "regulates" predicates for chemical to gene relations

### PR DESCRIPTION
**Pull request by edgargaticaCU**

### CODE REVIEW

**Comment by colleenXu** [comment]
@edgargaticaCU 

Feedback:
* Replace `activity or abundance` with snake-case `activity_or_abundance`. Sierra Moxon has confirmed that qualifier-values should be snake-case. So we're working on supporting that and changing our other x-bte annotations... 
* this comment can be removed: `## biolink 3.0.3: this is a mixin. Is this an issue?` 
    * regulates/regulated_by are also [not going to be mixins](https://github.com/biolink/biolink-model/commit/bf3711b46da3f3ec88fb9b48404748350b559686) in future biolink 3 versions

**Comment by edgargaticaCU** [comment]
@colleenXu Thank you for the feedback; I have made the necessary changes.

**Comment by colleenXu** [comment]
@edgargaticaCU Looks good to me. Do you have permissions to merge the PR yourself?

**Comment by edgargaticaCU** [comment]
@colleenXu I do not. No write access.

**Comment by colleenXu** [comment]
@edgargaticaCU Okay, I'll merge this for now. I think your team will need access in the future... @newgene

**Comment by newgene** [comment]
@edgargaticaCU just added you to this repo.

**Pull request merged**
